Repository woowacourse-teams/2023-shook, pull requests merged in 2023-09, with the labels that each got.

#372 Feat/#371: 회원 탈퇴 기능 구현
  backend/src/main/java/shook/shook/auth/config/AuthConfig.java
  backend/src/main/java/shook/shook/auth/exception/AuthorizationException.java
  backend/src/main/java/shook/shook/globalexception/ErrorCode.java
  backend/src/main/java/shook/shook/globalexception/GlobalExceptionHandler.java
  backend/src/main/java/shook/shook/member/application/MemberService.java
  backend/src/main/java/shook/shook/member/ui/MemberController.java
  backend/src/main/java/shook/shook/member/ui/openapi/MemberApi.java
  backend/src/main/resources/dev/data.sql
  backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java
  backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
  backend/src/test/java/shook/shook/member/ui/MemberControllerTest.java
Labels: [ 🌙 BE ], ✨ Feat

#352 Fix/#333 노래 상세정보 추가 fetch를 위한 인터섹션 옵저버 오류 수정
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/shared/hooks/useExtraFetch.ts
  frontend/src/shared/utils/createObserver.ts
Labels: 🦋 Bug, [ 🌞 FE ]

#358 Refactor/#357 @storybook/addon-styling 애드온 삭제
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: [ 🌞 FE ], ⚙️ Settin🐁

#391 Feat/#377 가입하기 전 로그인 패널 페이지를 만들고, 로그인 버튼으로 대체
  frontend/src/assets/icon/google-logo.svg
  frontend/src/assets/icon/kakao-logo.svg
  frontend/src/assets/image/shook-slogan.jpg
  frontend/src/pages/LoginPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/styles/theme.ts
Labels: [ 🌞 FE ], ✨ Feat

#399 Feat#398: 회원이 탈퇴시 회원의 댓글 좋아요를 모두 삭제한다.
  backend/src/main/java/shook/shook/member/application/MemberService.java
  backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepository.java
  backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepositoryTest.java
Labels: 🦋 Bug, [ 🌙 BE ]

#392 Feat/#382 EditProfilePage 구현 및 회원 탈퇴 기능 추가
  frontend/.gitignore
  frontend/src/features/auth/components/LoginModal.tsx
  frontend/src/features/comments/components/CommentForm.tsx
  frontend/src/features/member/components/WithdrawalModal.tsx
  frontend/src/features/member/constants/withdrawalMessage.ts
  frontend/src/features/member/remotes/member.ts
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/EditProfilePage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Layout/AuthLayout.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/remotes/index.ts
Labels: [ 🌞 FE ], ✨ Feat

#401 Refactor/#400 비로그인 상태로 댓글 작성 시도 시 로그인 권유 모달이 표시되도록 변경
  frontend/src/features/auth/components/LoginModal.tsx
  frontend/src/features/comments/components/CommentForm.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#409 Refactor/#408 SongDetailListPage의 Youtube Player 스크립트 로딩 성능 개선
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/pages/SongDetailListPage.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#422 Feat/#420 Song 도메인에 Genre 필드 추가
  backend/src/main/java/shook/shook/song/application/SongDataExcelReader.java
  backend/src/main/java/shook/shook/song/application/dto/SongWithKillingPartsRegisterRequest.java
  backend/src/main/java/shook/shook/song/domain/Genre.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/GenreTest.java
  backend/src/test/java/shook/shook/song/domain/SongTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/AdminSongControllerTest.java
  backend/src/test/resources/killingpart/initialize_killing_part_song.sql
  backend/src/test/resources/schema-test.sql
Labels: [ 🌙 BE ], ✨ Feat, 💿 Databas🦷

#435 Hotfix: 엑셀 노래 제목 데이터가 숫자로 구성된 상황을 처리한다.
  backend/src/main/java/shook/shook/song/application/SongDataExcelReader.java
Labels: 🦋 Bug, [ 🌙 BE ]

#424 Feat/#385 토큰을 관리하는 방식 수정
  backend/build.gradle
  backend/src/main/java/shook/shook/auth/application/AuthService.java
  backend/src/main/java/shook/shook/auth/application/TokenPairScheduler.java
  backend/src/main/java/shook/shook/auth/application/dto/ReissueAccessTokenResponse.java
  backend/src/main/java/shook/shook/auth/exception/TokenException.java
  backend/src/main/java/shook/shook/auth/repository/InMemoryTokenPairRepository.java
  backend/src/main/java/shook/shook/auth/ui/AccessTokenReissueController.java
  backend/src/main/java/shook/shook/auth/ui/openapi/AccessTokenReissueApi.java
  backend/src/main/java/shook/shook/globalexception/ErrorCode.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
  backend/src/test/java/shook/shook/auth/application/TokenPairSchedulerTest.java
  backend/src/test/java/shook/shook/auth/repository/InMemoryTokenPairRepositoryTest.java
  backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
  backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java
Labels: [ 🌙 BE ], ✨ Feat

#413 Feat/#412 사용자 분석을 위해 ga id 태그를 추가한다.
  frontend/public/index.html
Labels: [ 🌞 FE ], ✨ Feat

#439 Feat/#429 장르 카테고리 조회 API 구현
  backend/src/main/java/shook/shook/globalexception/ErrorCode.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/HighLikedSongResponse.java
  backend/src/main/java/shook/shook/song/domain/Genre.java
  backend/src/main/java/shook/shook/song/domain/InMemorySongs.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/exception/SongException.java
  backend/src/main/java/shook/shook/song/ui/HighLikedSongController.java
  backend/src/main/java/shook/shook/song/ui/SongController.java
  backend/src/main/java/shook/shook/song/ui/SongSwipeController.java
  backend/src/main/java/shook/shook/song/ui/openapi/HighLikedSongApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/SongApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/SongSwipeApi.java
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/song/application/InMemorySongsSchedulerTest.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/InMemorySongsTest.java
  backend/src/test/java/shook/shook/song/ui/HighLikedSongControllerTest.java
  backend/src/test/java/shook/shook/song/ui/SongControllerTest.java
  backend/src/test/java/shook/shook/song/ui/SongSwipeControllerTest.java
  backend/src/test/resources/killingpart/initialize_killing_part_song.sql
  backend/src/test/resources/schema-test.sql
Labels: [ 🌙 BE ], ✨ Feat

#428 Refactor/#427 ts-loader를 fork-ts-checker-webpack-plugin으로 대체한다
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: [ 🌞 FE ], 🔨 Refactor, ⚙️ Settin🐁

#440 Refactor/#433 서비스 메인페이지에 카테고리 별 목록을 추가하여 디자인을 개선한다.
  frontend/src/features/songs/components/CarouselItem.tsx
  frontend/src/features/songs/components/PopularSongItem.tsx
  frontend/src/features/songs/components/SongItem.stories.tsx
  frontend/src/features/songs/components/SongItem.tsx
  frontend/src/features/songs/components/SongItemList.tsx
  frontend/src/features/songs/components/Thumbnail.tsx
  frontend/src/features/songs/constants/genres.ts
  frontend/src/features/songs/remotes/song.ts
  frontend/src/features/songs/remotes/songs.ts
  frontend/src/features/songs/types/Song.type.ts
  frontend/src/mocks/fixtures/popularSongs.json
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/hooks/useExtraFetch.ts
  frontend/src/shared/hooks/useValidParams.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#432 Feat/#431 노래 상세 페이지에 스와이프 코치 마크를 구현한다
  frontend/src/assets/icon/swipe-up-down.svg
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/shared/components/Modal/Modal.tsx
  frontend/src/shared/hooks/useLocalStorage.ts
Labels: [ 🌞 FE ], ✨ Feat

#446 Feat/#406 access token 재발급 처리 및 카카오 로그인 추가
  frontend/src/features/auth/components/AuthProvider.tsx
  frontend/src/features/auth/components/LoginModal.tsx
  frontend/src/features/auth/constants/authUrls.ts
  frontend/src/features/auth/constants/googleAuthUrl.ts
  frontend/src/features/auth/hooks/LoginPopUpContext.tsx
  frontend/src/features/comments/components/CommentForm.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/index.tsx
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Layout/AuthLayout.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/hooks/useFetch.ts
  frontend/src/shared/hooks/useMutation.ts
  frontend/src/shared/remotes/AuthError.ts
  frontend/src/shared/remotes/index.ts
  frontend/src/shared/remotes/preCheckAccessToken.ts
  frontend/src/shared/utils/accessTokenStorage.ts
Labels: [ 🌞 FE ], ✨ Feat

#447 Hotfix: 스와이프 코치마크의 백드랍을 클릭하여도 모달이 닫히지 않도록 수정
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/shared/components/Modal/Modal.tsx
Labels: 🦋 Bug, [ 🌞 FE ]

#456 Fix/#445 preCheckAccessToken 로직 변경
  frontend/src/shared/remotes/preCheckAccessToken.ts
Labels: 🦋 Bug, [ 🌞 FE ]

#467 Refactor/#463, #468 캐러셀을 클릭했을 때 로그인이 안 된 경우 로그인 필요하다고 띄워준다
  frontend/src/features/songs/components/CarouselItem.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/router.tsx
  frontend/src/shared/styles/GlobalStyles.ts
Labels: [ 🌞 FE ], 🔨 Refactor, ✨ Feat

#454 Refactor/#443 캐러셀 컴포넌트 및 썸네일 컴포넌트 리팩터링
  frontend/src/features/songs/components/CarouselItem.tsx
  frontend/src/features/songs/components/CollectionCarousel.tsx
  frontend/src/features/songs/components/Thumbnail.tsx
Labels: [ 🌞 FE ], ✨ Feat

#471 Feat/#460 GA 이벤트 추가
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/shared/constants/GAEventName.ts
  frontend/src/shared/googleAnalytics/sendGAEvent.ts
  frontend/src/shared/types/ga.d.ts
Labels: [ 🌞 FE ], ✨ Feat

#469 Refactor/#461 같은 멤버가 등록중인 노래에 같은 부분을 킬링파트로 등록시 추가 데이터를 저장하지 않는 기능 구현
  backend/src/main/java/shook/shook/voting_song/application/VotingSongPartService.java
  backend/src/main/java/shook/shook/voting_song/domain/Vote.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongParts.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VoteRepository.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongPartRepository.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongPartController.java
  backend/src/main/java/shook/shook/voting_song/ui/openapi/VotingSongPartApi.java
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongPartServiceTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartsTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VoteRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/ui/VotingSongPartControllerTest.java
  backend/src/test/resources/schema-test.sql
Labels: [ 🌙 BE ], 🔨 Refactor

#484 Hotfix/#483 마이페이지에서 좋아요한 노래 아이템 클릭시 노래 듣기로 이동
  frontend/src/pages/MyPage.tsx
Labels: [ 🌞 FE ]
