Repository woowacourse-teams/2023-shook, pull requests merged in 2023-10, with the labels that each got.

#485 Feat/#472 스와이프시 url이 변경되도록 한다.
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
  frontend/src/features/youtube/components/Youtube.tsx
Labels: [ 🌞 FE ], ✨ Feat

#503 Feat/#492 가수 검색 기능을 구현한다.
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icon/left-arrow.svg
  frontend/src/assets/icon/search.svg
  frontend/src/features/auth/components/AuthProvider.tsx
  frontend/src/features/auth/hooks/LoginPopUpContext.tsx
  frontend/src/features/search/components/SearchBar.stories.tsx
  frontend/src/features/search/components/SearchBar.tsx
  frontend/src/features/search/components/SearchPreviewSheet.tsx
  frontend/src/features/search/hooks/useSearchBar.ts
  frontend/src/features/search/remotes/search.ts
  frontend/src/features/search/types/search.ts
  frontend/src/features/songs/components/Thumbnail.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/fixtures/searchedSingerPreview.json
  frontend/src/mocks/fixtures/searchedSingers.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/searchHandlers.ts
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/SearchResultPage.tsx
  frontend/src/pages/SingerDetailPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Flex/Flex.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/hooks/useValidSearchParams.ts
Labels: [ 🌞 FE ], ✨ Feat

#494 Refactor/#215 댓글 시간을 시간,일,달 등 자세하게 표시한다
  frontend/src/features/comments/components/Comment.tsx
  frontend/src/shared/utils/convertRelativeTimeString.test.ts
  frontend/src/shared/utils/convertRelativeTimeString.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#520 Refactor/#518 frontend prod CD에 npm 캐시 추가
  .github/workflows/frontend-ci.yml
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
Labels: 🔨 Refactor, 🤖 InfrA, 🐈‍⬛ Github

#522 config: schema에서 legacy_length 열 삭제
  backend/src/main/resources/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#521 Feat/#514 무중단 배포를 위한 Actuator 추가, Profile API 생성
  backend/build.gradle
  backend/src/main/java/shook/shook/status/ProfileCheckController.java
  backend/src/main/java/shook/shook/status/response/ProfileResponse.java
  backend/src/main/java/shook/shook/status/response/ReservedProfiles.java
Labels: [ 🌙 BE ], 🤖 InfrA

#507 Feat/#506 마이파트를 등록하는 기능을 추가한다
  frontend/src/assets/icon/trash.svg
  frontend/src/features/member/components/MyPartList.tsx
  frontend/src/features/member/components/PartItem.tsx
  frontend/src/features/member/components/PartList.tsx
  frontend/src/features/member/constants/introductions.ts
  frontend/src/features/member/remotes/memberParts.ts
  frontend/src/features/member/remotes/myPage.ts
  frontend/src/features/member/types/myPage.ts
  frontend/src/features/member/utils/getRandomIntroduction.ts
  frontend/src/features/songs/components/CollectionCarousel.tsx
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/songs/components/KillingPartTrack.stories.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
  frontend/src/features/songs/components/KillingPartTrackList.tsx
  frontend/src/features/songs/components/MyPartModal.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
  frontend/src/features/songs/constants/genres.ts
  frontend/src/mocks/fixtures/likeParts.json
  frontend/src/mocks/fixtures/myParts.json
  frontend/src/mocks/fixtures/songEntries.json
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/MyPage.tsx
  frontend/src/shared/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#524 hotfix: 메인 페이지 조회 시 토큰 받지 않도록 수정
  backend/src/main/java/shook/shook/auth/config/AuthConfig.java
Labels: 🦋 Bug, [ 🌙 BE ]

#526 Refactor/#505 댓글 기능을 임시 중단하고 킬링파트 듣기 페이지의 디자인을 수정한다.
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/songs/components/KillingPartTrackList.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
Labels: [ 🌞 FE ], ✨ Feat

#527 hotfix: dev schema 변경된 내용 반영
  backend/src/main/resources/dev/data.sql
  backend/src/main/resources/dev/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#528 Hotfix/dev schema 최신화
  backend/src/main/resources/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#529 Hotfix/dev schema
  backend/src/main/resources/dev/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#530 hotfix: prod schema 롤백
  backend/src/main/resources/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#531 config: dev schema 동기화
  backend/src/main/resources/dev/schema.sql
Labels: 🦋 Bug, [ 🌙 BE ]

#533 Hotfix#505 sm 이하 넓이에서는 컨테이너가 flex-start가 되도록 변경
  frontend/src/features/songs/components/SongDetailItem.tsx
Labels: 🦋 Bug, [ 🌞 FE ]

#508 Feat/#499 등록 ui 개선 및 등록 페이지 리팩터링
  frontend/src/assets/icon/pin.svg
  frontend/src/assets/icon/play-stream.svg
  frontend/src/assets/icon/remove.svg
  frontend/src/features/killingParts/components/RegisterPart.tsx
  frontend/src/features/killingParts/components/SoundWave.tsx
  frontend/src/features/killingParts/components/VideoBadges.tsx
  frontend/src/features/killingParts/components/VideoController.tsx
  frontend/src/features/killingParts/components/VideoIntervalStepper.tsx
  frontend/src/features/killingParts/components/WaveScrubber.tsx
  frontend/src/features/killingParts/hooks/killingPart.ts
  frontend/src/features/killingParts/hooks/useCollectingPartContext.ts
  frontend/src/features/killingParts/hooks/usePin.ts
  frontend/src/features/killingParts/hooks/useWave.ts
  frontend/src/features/killingParts/remotes/usePostKillingPart.ts
  frontend/src/features/search/hooks/useSearchBar.ts
  frontend/src/features/songs/components/CollectingPartProvider.tsx
  frontend/src/features/songs/components/IntervalInput.stories.tsx
  frontend/src/features/songs/components/IntervalInput.tsx
  frontend/src/features/songs/components/KillingPartToggleGroup.tsx
  frontend/src/features/songs/components/SongInformation.tsx
  frontend/src/features/songs/components/Thumbnail.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/songs/components/VoteInterfaceProvider.tsx
  frontend/src/features/songs/constants/partInterval.ts
  frontend/src/features/songs/hooks/useVoteInterfaceContext.ts
  frontend/src/features/youtube/components/VideoPlayerProvider.tsx
  frontend/src/features/youtube/components/VideoSlider.tsx
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/shared/components/Layout/Layout.tsx
  frontend/src/shared/hooks/useDebounceEffect.ts
  frontend/src/shared/styles/GlobalStyles.ts
  frontend/src/shared/styles/theme.ts
  frontend/src/shared/types/killingPart.ts
  frontend/src/shared/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#525 Feat/#513, #523 검색완료, 가수 상세 페이지 구현 및 메인페이지 케러셀 정책 변경 반영
  frontend/src/assets/icon/right-long-arrow.svg
  frontend/src/features/search/components/SearchBar.stories.tsx
  frontend/src/features/search/components/SearchPreviewSheet.stories.tsx
  frontend/src/features/search/components/SearchPreviewSheet.tsx
  frontend/src/features/search/remotes/search.ts
  frontend/src/features/search/types/search.type.ts
  frontend/src/features/singer/components/SingerBanner.stories.tsx
  frontend/src/features/singer/components/SingerBanner.tsx
  frontend/src/features/singer/components/SingerSongItem.stories.tsx
  frontend/src/features/singer/components/SingerSongItem.tsx
  frontend/src/features/singer/components/SingerSongList.stories.tsx
  frontend/src/features/singer/components/SingerSongList.tsx
  frontend/src/features/singer/remotes/singer.ts
  frontend/src/features/singer/types/singer.type.ts
  frontend/src/features/songs/components/CarouselItem.tsx
  frontend/src/features/songs/components/CollectionCarousel.stories.tsx
  frontend/src/features/songs/components/KillingPartTrack.stories.tsx
  frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
  frontend/src/features/songs/components/SongItem.stories.tsx
  frontend/src/features/songs/remotes/song.ts
  frontend/src/features/songs/remotes/useGetSongDetail.ts
  frontend/src/mocks/fixtures/recentSongs.json
  frontend/src/mocks/fixtures/searchedSingers.json
  frontend/src/mocks/fixtures/songEntries.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/searchHandlers.ts
  frontend/src/mocks/handlers/singerHandlers.ts
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SearchResultPage.tsx
  frontend/src/pages/SingerDetailPage.tsx
  frontend/src/shared/components/BottomSheet/BottomSheet.stories.tsx
  frontend/src/shared/components/Modal/Modal.stories.tsx
  frontend/src/shared/components/Spacing.tsx
  frontend/src/shared/components/Toast/Toast.stories.tsx
  frontend/src/shared/components/ToggleSwitch/ToggleSwitch.stories.tsx
  frontend/src/shared/styles/GlobalStyles.ts
  frontend/src/shared/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#535 Feat/#534 Shook Layout (Flex 컴포넌트) 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/killingParts/components/VideoBadges.tsx
  frontend/src/features/killingParts/components/VideoController.tsx
  frontend/src/features/killingParts/components/VideoIntervalStepper.tsx
  frontend/src/features/killingParts/components/WaveScrubber.tsx
  frontend/src/features/search/components/SearchBar.tsx
  frontend/src/features/search/components/SearchPreviewSheet.tsx
  frontend/src/features/singer/components/SingerBanner.tsx
  frontend/src/features/singer/components/SingerSongItem.tsx
  frontend/src/features/singer/components/SingerSongList.tsx
  frontend/src/features/songs/components/KillingPartInfo.tsx
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
  frontend/src/features/songs/components/SongInformation.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/pages/SearchResultPage.tsx
  frontend/src/pages/SingerDetailPage.tsx
  frontend/src/shared/components/Flex.tsx
  frontend/src/shared/components/Flex/Flex.tsx
  frontend/src/shared/components/Layout/Header.tsx
Labels: [ 🌞 FE ], ✨ Feat

#540 Fix/#536 메인 서브 타이틀 변경 및 듣기 인터페이스 버튼 title 문구 삭제
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/SongItemList.tsx
  frontend/src/features/songs/constants/genres.ts
  frontend/src/pages/MainPage.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#548 Fix/#547 킬링파트 여러 사용자 동시 좋아요 누를 때 동시성 이슈 해결
  backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepository.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartRepository.java
  backend/src/test/java/shook/shook/song/application/killingpart/KillingPartLikeConcurrencyTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
Labels: 🦋 Bug, [ 🌙 BE ]
