Repository woowacourse-teams/2023-shook, pull requests merged in 2023-07, with the labels that each got.

#40 Feat/#32 백엔드 프로젝트 환경 설정
  .idea/.gitignore
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/shook/shook/ShookApplication.java
  backend/src/test/java/shook/shook/ShookApplicationTests.java
Labels: [ 백엔드 ], 환경 설정

#45 Feat/#27: Song, Vote 도메인 생성
  backend/src/main/java/shook/shook/part/domain/Part.java
  backend/src/main/java/shook/shook/part/domain/PartLength.java
  backend/src/main/java/shook/shook/song/domain/Length.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/vote/domain/Vote.java
Labels: [ 백엔드 ], feat

#61 [FEAT] PR 등록 시 자동으로 리뷰어를 등록하는 기능 추가
  .github/CODEOWNERS
Labels: Github 설정

#56 Feat/#29: 노래 등록 조회, 파트 등록, 킬링파트 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/shook/shook/ShookApplication.java
  backend/src/main/java/shook/shook/part/application/PartService.java
  backend/src/main/java/shook/shook/part/application/dto/PartRegisterRequest.java
  backend/src/main/java/shook/shook/part/domain/Part.java
  backend/src/main/java/shook/shook/part/domain/PartLength.java
  backend/src/main/java/shook/shook/part/domain/Vote.java
  backend/src/main/java/shook/shook/part/domain/repository/PartRepository.java
  backend/src/main/java/shook/shook/part/domain/repository/VoteRepository.java
  backend/src/main/java/shook/shook/part/exception/PartException.java
  backend/src/main/java/shook/shook/part/exception/VoteException.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartsResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/domain/Parts.java
  backend/src/main/java/shook/shook/song/domain/Singer.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/domain/SongLength.java
  backend/src/main/java/shook/shook/song/domain/SongTitle.java
  backend/src/main/java/shook/shook/song/domain/SongVideoUrl.java
  backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
  backend/src/main/java/shook/shook/song/exception/SongException.java
  backend/src/main/java/shook/shook/util/StringChecker.java
  backend/src/test/java/shook/shook/part/application/PartServiceTest.java
  backend/src/test/java/shook/shook/part/domain/PartLengthTest.java
  backend/src/test/java/shook/shook/part/domain/PartTest.java
  backend/src/test/java/shook/shook/part/domain/repository/PartRepositoryTest.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/PartsTest.java
  backend/src/test/java/shook/shook/song/domain/SingerTest.java
  backend/src/test/java/shook/shook/song/domain/SongLengthTest.java
  backend/src/test/java/shook/shook/song/domain/SongTest.java
  backend/src/test/java/shook/shook/song/domain/SongTitleTest.java
  backend/src/test/java/shook/shook/song/domain/SongVideoUrlTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/support/UsingJpaTest.java
  backend/src/test/java/shook/shook/util/StringCheckerTest.java
Labels: [ 백엔드 ], feat

#75 config: CI 트리거 추가
  .github/workflows/backend-ci.yml
Labels: 인프라

#78 Feat/#71: DB 스키마 작성 및 개발 환경 더미 데이터 스크립트 작성
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: [ 백엔드 ], 인프라, 데이터베이스

#79 Config: 워크 플로우 수동 동작 트리거 추가
  .github/workflows/backend-ci.yml
Labels: Github 설정

#69 Feat/#58 IntervalInput 컴포넌트 (킬링파트 등록 시간 input) 구현
  frontend/src/components/IntervalInput/IntervalInput.stories.tsx
  frontend/src/components/IntervalInput/IntervalInput.style.ts
  frontend/src/components/IntervalInput/IntervalInput.test.tsx
  frontend/src/components/IntervalInput/IntervalInput.tsx
  frontend/src/components/IntervalInput/IntervalInput.type.ts
  frontend/src/components/IntervalInput/constants/errorMessage.ts
  frontend/src/components/IntervalInput/hooks/useIntervalInput.ts
  frontend/src/components/IntervalInput/index.ts
  frontend/src/utils/convertTime.test.ts
  frontend/src/utils/convertTime.ts
  frontend/src/utils/validateTime.test.ts
  frontend/src/utils/validateTime.ts
Labels: [ 🌞 FE ], ✨ Feat

#67 Feat/#60 킬링파트 구간을 선택하는 토글버튼그룹 구현
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.stories.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.style.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.type.ts
  frontend/src/components/KillingPartToggleGroup/constants.ts
  frontend/src/components/KillingPartToggleGroup/index.tsx
Labels: [ 🌞 FE ], ✨ Feat

#72 Feat/#68 모달 컴포넌트를 구현한다
  frontend/src/components/Modal/Modal.stories.tsx
  frontend/src/components/Modal/Modal.style.ts
  frontend/src/components/Modal/Modal.test.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/hooks/useModal.test.ts
  frontend/src/components/Modal/hooks/useModal.ts
  frontend/src/components/Modal/index.ts
  frontend/src/pages/SongDetailPage.style.ts
  frontend/src/pages/SongDetailPage.tsx
Labels: [ 🌞 FE ], ✨ Feat

#73 Feat/#59 토스트 컴포넌트 구현
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icon/toast-success.svg
  frontend/src/components/@common/Toast/Toast.stories.tsx
  frontend/src/components/@common/Toast/Toast.style.tsx
  frontend/src/components/@common/Toast/Toast.tsx
  frontend/src/components/@common/Toast/ToastList.tsx
  frontend/src/components/@common/Toast/ToastProvider.tsx
  frontend/src/components/@common/Toast/hooks/useToastContext.ts
  frontend/src/components/@common/Toast/keyframes/fadeInBottomToUp.ts
  frontend/src/components/Layout/Header.tsx
  frontend/src/components/Layout/Layout.tsx
  frontend/src/index.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/types/assets.d.ts
  frontend/src/types/styled-components.d.ts
  frontend/src/types/theme.ts
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: [ 🌞 FE ], ✨ Feat

#88 Feat/#87: 파트 등록, 노래 정보 조회 API 구현
  backend/build.gradle
  backend/src/main/java/shook/shook/part/application/PartService.java
  backend/src/main/java/shook/shook/part/application/dto/PartRegisterRequest.java
  backend/src/main/java/shook/shook/part/application/dto/PartRegisterResponse.java
  backend/src/main/java/shook/shook/part/domain/Part.java
  backend/src/main/java/shook/shook/part/ui/PartController.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartsResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/domain/Parts.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/ui/SongController.java
  backend/src/test/java/shook/shook/part/application/PartServiceTest.java
  backend/src/test/java/shook/shook/part/domain/PartTest.java
  backend/src/test/java/shook/shook/part/ui/PartControllerTest.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/PartsTest.java
  backend/src/test/java/shook/shook/song/ui/SongControllerTest.java
Labels: [ 🌙 BE ], ✨ Feat

#99 Feat/#95 킬링파트 등록 & 노래 상세 정보 API 로직을 구현
  frontend/src/apis/index.ts
  frontend/src/apis/killingPart.ts
  frontend/src/apis/song.ts
  frontend/src/hooks/@common/useFetch.ts
  frontend/src/hooks/@common/useMutation.ts
  frontend/src/hooks/killingPart.ts
  frontend/src/hooks/song.ts
  frontend/src/types/killingPart.ts
  frontend/src/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#118 Feat/#114 유튜브 iframe api 타입 정의(YT)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/types/youtube.d.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#122 Feat/#109 환경설정 수정 및 추가
  frontend/.eslintrc.js
  frontend/package.json
  frontend/webpack.dev.js
Labels: [ 🌞 FE ], ⚙️ Settin🐁

#133 Feat/#98 개발 환경, 배포 환경 yml 분리
  backend/src/main/resources/application.yml
Labels: [ 🌙 BE ], ⚙️ Settin🐁

#129 Feat/#123 프론트엔드 테스트 CI (lint, test, build)
  .github/workflows/frontend-ci.yml
Labels: [ 🌞 FE ], ⚙️ Settin🐁

#137 Fix/#136 npm ci 실행 step 추가
  .github/workflows/frontend-ci.yml
Labels: 🦋 Bug, [ 🌞 FE ]

#138 Fix/#136 working directory 작성 및 if 절 순서 변경
  .github/workflows/frontend-ci.yml
Labels: 🦋 Bug, [ 🌞 FE ]

#132 Feat/#120 .env 환경 변수 설정 및 MSW 설정
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/index.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/fixtures/songs.json
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/webpack.common.js
Labels: [ 🌞 FE ], ⚙️ Settin🐁

#142 Fix/#141 폴더 상관없이 항상 CI를 실행하도록 변경
  .github/workflows/backend-ci.yml
  .github/workflows/frontend-ci.yml
Labels: 🦋 Bug, [ 🌙 BE ], [ 🌞 FE ]

#135 Refactor/#121 페이지 레이아웃 및 반응형 디자인 통일
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/assets/icon/shook-logo.svg
  frontend/src/assets/image/album-jacket.png
  frontend/src/components/IntervalInput/IntervalInput.style.ts
  frontend/src/components/IntervalInput/IntervalInput.test.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.style.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.tsx
  frontend/src/components/Layout/Header.tsx
  frontend/src/components/Layout/Layout.tsx
  frontend/src/components/Modal/Modal.test.tsx
  frontend/src/components/VideoSlider/VideoSlider.style.ts
  frontend/src/components/Youtube/Youtube.tsx
  frontend/src/pages/SongDetailPage.style.ts
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/renderWithTheme.tsx
  frontend/tsconfig.json
Labels: [ 🌞 FE ], 🔨 Refactor

#155 Feat/#154 윈도우 환경변수 주입 오류 해결
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: [ 🌞 FE ], ⚙️ Settin🐁
