Repository woowacourse-teams/2023-shook, pull requests merged in 2023-08, with the labels that each got.

#168 Feat/#167: 백엔드 CD 설정 추가
  .github/workflows/backend-dev-cd.yml
Labels: [ 🌙 BE ], ⚙️ Settin🐁, 🤖 InfrA, 🐈‍⬛ Github

#169 Feat/#167 백엔드 CD pwd 로깅 추가
  .github/workflows/backend-dev-cd.yml
Labels: [ 🌙 BE ], ⚙️ Settin🐁, 🤖 InfrA, 🐈‍⬛ Github

#181 Hotfix: profile 오류로 인한 application.yml 수정
  backend/src/main/resources/application.yml
Labels: 🦋 Bug, [ 🌙 BE ]

#146 Feat/#134 파트에 댓글 작성 기능 추가
  backend/src/main/java/shook/shook/part/application/PartCommentService.java
  backend/src/main/java/shook/shook/part/application/dto/PartCommentRegisterRequest.java
  backend/src/main/java/shook/shook/part/application/dto/PartCommentResponse.java
  backend/src/main/java/shook/shook/part/domain/Part.java
  backend/src/main/java/shook/shook/part/domain/PartComment.java
  backend/src/main/java/shook/shook/part/domain/PartCommentContent.java
  backend/src/main/java/shook/shook/part/domain/PartComments.java
  backend/src/main/java/shook/shook/part/domain/repository/PartCommentRepository.java
  backend/src/main/java/shook/shook/part/exception/PartCommentException.java
  backend/src/main/java/shook/shook/part/ui/PartCommentController.java
  backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/part/application/PartCommentServiceTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentContentTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentsTest.java
  backend/src/test/java/shook/shook/part/domain/PartTest.java
  backend/src/test/java/shook/shook/part/domain/repository/PartCommentRepositoryTest.java
  backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
Labels: [ 🌙 BE ], ✨ Feat

#183 Feat/#162 swagger 의존성 추가
  backend/build.gradle
Labels: [ 🌙 BE ], ⚙️ Settin🐁

#177 Feat/#176 Layout을 수정한다 (Header, layout color)
  frontend/src/components/Layout/Header.tsx
  frontend/src/components/Layout/Layout.tsx
Labels: [ 🌞 FE ], ✨ Feat

#175 Feat/#166 메인페이지에서 킬링파트 등록 인기순 음악을 보여준다
  frontend/src/assets/icon/album-jacket-default.svg
  frontend/src/components/PopularSongItem/PopularSongItem.stories.tsx
  frontend/src/components/PopularSongItem/PopularSongItem.style.ts
  frontend/src/components/PopularSongItem/PopularSongItem.tsx
  frontend/src/components/PopularSongItem/Thumbnail.style.ts
  frontend/src/components/PopularSongItem/Thumbnail.tsx
  frontend/src/components/PopularSongItem/index.ts
  frontend/src/mocks/fixtures/popularSongs.json
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/SongPopularPage/SongPopularPage.style.ts
  frontend/src/pages/SongPopularPage/SongPopularPage.tsx
  frontend/src/pages/SongPopularPage/index.ts
  frontend/src/router.tsx
Labels: [ 🌞 FE ], ✨ Feat

#182 Feat/#165 기본 폰트를 설정한다 - 프리텐다드
  frontend/src/assets/fonts/Pretendard-Regular.subset.woff2
  frontend/src/assets/fonts/Pretendard.stories.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/types/assets.d.ts
  frontend/webpack.common.js
Labels: [ 🌞 FE ], ⚙️ Settin🐁

#179 Refactor/#143 킬링파트 등록 페이지 및 연관 컴포넌트 일괄 리팩토링
  frontend/src/components/IntervalInput/IntervalInput.stories.tsx
  frontend/src/components/IntervalInput/IntervalInput.test.tsx
  frontend/src/components/IntervalInput/IntervalInput.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.stories.tsx
  frontend/src/components/KillingPartToggleGroup/KillingPartToggleGroup.tsx
  frontend/src/components/VideoSlider/VideoSlider.tsx
  frontend/src/components/VoteInterface/VoteInterface.style.ts
  frontend/src/components/VoteInterface/VoteInterface.tsx
  frontend/src/components/VoteInterface/VoteInterfaceProvider.tsx
  frontend/src/components/VoteInterface/hooks/useVoteInterfaceContext.ts
  frontend/src/components/VoteInterface/index.ts
  frontend/src/components/Youtube/VideoPlayerProvider.tsx
  frontend/src/components/Youtube/Youtube.tsx
  frontend/src/components/Youtube/api/loadIframeApi.ts
  frontend/src/components/Youtube/hooks/useVideoPlayerContext.ts
  frontend/src/components/Youtube/index.ts
  frontend/src/pages/SongDetailPage.style.ts
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/pages/SongPage/SongPage.style.tsx
  frontend/src/pages/SongPage/SongPage.tsx
  frontend/src/pages/SongPopularPage/SongPopularPage.tsx
  frontend/src/router.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#190 Hotfix: KillingPartResponse 에 id 추가
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
Labels: [ 🌙 BE ], 🔨 Refactor

#194 Fix/#192 Spacing "min-" 스타일 속성을 통해 빌드시에도 스타일 유지
  frontend/src/components/@common/Spacing.tsx
  frontend/src/components/IntervalInput/IntervalInput.test.tsx
  frontend/svgTransform.js
Labels: 🦋 Bug, [ 🌞 FE ]

#195 Hotfix: SongResponse 에 albumCoverUrl 추가
  backend/src/main/java/shook/shook/song/application/dto/HighVotedSongResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/domain/AlbumCoverUrl.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/song/domain/AlbumCoverUrlTest.java
  backend/src/test/resources/test.sql
Labels: [ 🌙 BE ], 🔨 Refactor

#197 Feat/#196 albumCoverUrl (앨범 이미지) 필드 변경으로 인한 수정
  frontend/src/assets/image/album-jacket.png
  frontend/src/components/PopularSongItem/PopularSongItem.stories.tsx
  frontend/src/components/PopularSongItem/PopularSongItem.tsx
  frontend/src/mocks/fixtures/popularSongs.json
  frontend/src/mocks/fixtures/songs.json
  frontend/src/pages/SongDetailPage.style.ts
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/pages/SongPage/SongPage.style.tsx
  frontend/src/pages/SongPage/SongPage.tsx
  frontend/src/pages/SongPopularPage/SongPopularPage.tsx
  frontend/src/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#189 Feat/#187 노래(킬링파트) 조회 페이지 웹 접근성 추가
  frontend/src/components/@common/SRAlert.tsx
  frontend/src/components/@common/SRHeading.tsx
  frontend/src/components/@common/Toast/Toast.tsx
  frontend/src/components/@common/ToggleGroup/ToggleGroup.tsx
  frontend/src/components/@common/ToggleSwitch/ToggleSwitch.stories.tsx
  frontend/src/components/@common/ToggleSwitch/ToggleSwitch.tsx
  frontend/src/components/KillingPartInfo/KillingPartInfo.tsx
  frontend/src/components/Layout/Header.tsx
  frontend/src/pages/SongPage/SongPage.tsx
Labels: [ 🌞 FE ], ✨ Feat

#200 Hotfix: SongResponse KillingPart id 수정
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
Labels: 🦋 Bug, [ 🌙 BE ]

#199 Feat/#188 조회 페이지 댓글 기능
  frontend/src/assets/icon/shookshook.svg
  frontend/src/components/CommentList/Comment.tsx
  frontend/src/components/CommentList/CommentList.tsx
  frontend/src/components/CommentList/index.ts
  frontend/src/components/VoteInterface/VoteInterface.tsx
  frontend/src/hooks/@common/useFetch.ts
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/SongDetailPage.style.ts
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/pages/SongPage/SongPage.style.tsx
  frontend/src/pages/SongPage/SongPage.tsx
  frontend/src/pages/SongPopularPage/SongPopularPage.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#202 Feat/#198 노래 듣기 페이지 웹 접근성 수정
  frontend/src/components/@common/SRHeading.tsx
  frontend/src/components/@common/ToggleGroup/ToggleGroup.tsx
  frontend/src/components/CommentList/CommentList.tsx
  frontend/src/components/PopularSongItem/PopularSongItem.style.ts
  frontend/src/components/PopularSongItem/PopularSongItem.tsx
  frontend/src/components/PopularSongItem/Thumbnail.tsx
  frontend/src/components/Youtube/Youtube.tsx
  frontend/src/pages/SongPage/SongPage.tsx
  frontend/src/pages/SongPopularPage/SongPopularPage.tsx
Labels: [ 🌞 FE ], ✨ Feat

#205 Refactor/#204 컴포넌트 중복 코드 삭제 및 msw 핸들러 추가 및 수정
  frontend/src/components/VoteInterface/VoteInterface.tsx
  frontend/src/mocks/fixtures/songs.json
  frontend/src/mocks/handlers/songsHandlers.ts
Labels: [ 🌞 FE ], 🔨 Refactor, ✨ Feat

#222 Refactor/#161 router 정리
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/pages/SongPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/constants/path.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#223 Fix/#208 댓글 입력시 양쪽 공백 제거
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/pages/MainPage.tsx
Labels: 🦋 Bug, [ 🌞 FE ]

#157 Feat/#130 구글 소셜 로그인 구현
  backend/build.gradle
  backend/src/main/java/shook/shook/auth/jwt/application/TokenProvider.java
  backend/src/main/java/shook/shook/auth/jwt/exception/TokenException.java
  backend/src/main/java/shook/shook/auth/oauth/application/GoogleInfoProvider.java
  backend/src/main/java/shook/shook/auth/oauth/application/OAuthService.java
  backend/src/main/java/shook/shook/auth/oauth/application/dto/GoogleAccessTokenRequest.java
  backend/src/main/java/shook/shook/auth/oauth/application/dto/GoogleAccessTokenResponse.java
  backend/src/main/java/shook/shook/auth/oauth/application/dto/GoogleMemberInfoResponse.java
  backend/src/main/java/shook/shook/auth/oauth/application/dto/LoginResponse.java
  backend/src/main/java/shook/shook/auth/oauth/config/OAuthConfig.java
  backend/src/main/java/shook/shook/auth/oauth/exception/OAuthException.java
  backend/src/main/java/shook/shook/auth/oauth/ui/OauthController.java
  backend/src/main/java/shook/shook/member/application/MemberService.java
  backend/src/main/java/shook/shook/member/application/dto/MemberRegisterRequest.java
  backend/src/main/java/shook/shook/member/domain/Email.java
  backend/src/main/java/shook/shook/member/domain/Member.java
  backend/src/main/java/shook/shook/member/domain/Nickname.java
  backend/src/main/java/shook/shook/member/domain/repository/MemberRepository.java
  backend/src/main/java/shook/shook/member/exception/MemberException.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/auth/jwt/application/TokenProviderTest.java
  backend/src/test/java/shook/shook/auth/oauth/application/GoogleInfoProviderTest.java
  backend/src/test/java/shook/shook/auth/oauth/application/OAuthServiceTest.java
  backend/src/test/java/shook/shook/auth/oauth/ui/OauthControllerTest.java
  backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
  backend/src/test/java/shook/shook/member/domain/EmailTest.java
  backend/src/test/java/shook/shook/member/domain/NickNameTest.java
  backend/src/test/resources/application.yml
Labels: [ 🌙 BE ], ✨ Feat

#225 Fix/#212 길이 선택 버튼 클릭시 영상 최대 길이를 넘어선 값으로 표시되던 버그 수정
  frontend/src/features/songs/components/IntervalInput.stories.tsx
  frontend/src/features/songs/components/IntervalInput.tsx
  frontend/src/features/songs/components/KillingPartToggleGroup.stories.tsx
  frontend/src/features/songs/components/KillingPartToggleGroup.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/songs/components/VoteInterfaceProvider.tsx
  frontend/src/features/songs/hooks/useKillingPartInterval.ts
  frontend/src/features/youtube/components/VideoSlider.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/shared/utils/convertTime.test.ts
  frontend/src/shared/utils/convertTime.ts
Labels: 🦋 Bug, [ 🌞 FE ]

#227 Refactor/#224 PartCollectingPage에서 Input 기능 삭제 및 선택 구간 표시기능 구현
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/youtube/components/VideoSlider.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#242 Feat/#233 킬링파트 트랙 컴포넌트 구현
  frontend/src/assets/icon/empty-heart.svg
  frontend/src/assets/icon/empty-play.svg
  frontend/src/assets/icon/fill-heart.svg
  frontend/src/assets/icon/fill-play.svg
  frontend/src/assets/icon/share.svg
  frontend/src/assets/icon/shook.svg
  frontend/src/features/songs/components/KillingPartTrack.stories.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
  frontend/src/features/songs/components/KillingPartTrackList.tsx
  frontend/src/features/songs/constants/killingPartRank.ts
  frontend/src/features/songs/types/KillingPartRank.type.ts
  frontend/src/shared/styles/theme.ts
  frontend/src/shared/types/killingPart.ts
  frontend/src/shared/types/song.ts
  frontend/src/shared/utils/formatOrdinals.ts
Labels: [ 🌞 FE ], ✨ Feat

#239 Refactor: KillingPart 도메인, 서비스 생성
  backend/src/main/java/shook/shook/song/application/killingpart/KillingPartCommentService.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/KillingPartCommentRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/KillingPartCommentResponse.java
  backend/src/main/java/shook/shook/song/domain/KillingParts.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartComment.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartCommentContent.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartComments.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepository.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartRepository.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartCommentException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartsException.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartCommentContentTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartCommentTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartCommentsTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartsTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#245 Feat/#243 기존의 Song, Part, Vote 를 VotingSong, VotingSongPart, Register 로 리팩터링
  backend/src/main/java/shook/shook/voting_song/application/VotingSongPartService.java
  backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongPartRegisterRequest.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongRegisterRequest.java
  backend/src/main/java/shook/shook/voting_song/domain/Register.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSong.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongParts.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/RegisterRepository.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongPartRepository.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongRepository.java
  backend/src/main/java/shook/shook/voting_song/exception/RegisterException.java
  backend/src/main/java/shook/shook/voting_song/exception/VotingSongException.java
  backend/src/main/java/shook/shook/voting_song/exception/VotingSongPartException.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongPartController.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/part/domain/repository/PartRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongPartServiceTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongServiceTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartsTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
  backend/src/test/resources/test.sql
Labels: [ 🌙 BE ], 🔨 Refactor

#252 Refactor: Song, VotingSong 분리
  backend/src/main/java/shook/shook/part/application/PartCommentService.java
  backend/src/main/java/shook/shook/part/application/PartService.java
  backend/src/main/java/shook/shook/part/application/dto/PartCommentRegisterRequest.java
  backend/src/main/java/shook/shook/part/application/dto/PartCommentResponse.java
  backend/src/main/java/shook/shook/part/application/dto/PartRegisterRequest.java
  backend/src/main/java/shook/shook/part/application/dto/PartRegisterResponse.java
  backend/src/main/java/shook/shook/part/domain/Part.java
  backend/src/main/java/shook/shook/part/domain/PartCommentContent.java
  backend/src/main/java/shook/shook/part/domain/PartComments.java
  backend/src/main/java/shook/shook/part/domain/Vote.java
  backend/src/main/java/shook/shook/part/domain/repository/PartCommentRepository.java
  backend/src/main/java/shook/shook/part/domain/repository/PartRepository.java
  backend/src/main/java/shook/shook/part/exception/PartCommentException.java
  backend/src/main/java/shook/shook/part/exception/PartException.java
  backend/src/main/java/shook/shook/part/ui/PartCommentController.java
  backend/src/main/java/shook/shook/part/ui/PartController.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/HighVotedSongResponse.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartsResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/domain/Parts.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
  backend/src/main/java/shook/shook/song/domain/repository/dto/SongTotalVoteCountDto.java
  backend/src/main/java/shook/shook/song/ui/HighVotedSongController.java
  backend/src/main/java/shook/shook/song/ui/SongController.java
  backend/src/main/java/shook/shook/voting_song/application/VotingSongPartService.java
  backend/src/main/java/shook/shook/voting_song/domain/Register.java
  backend/src/main/java/shook/shook/voting_song/domain/Vote.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/RegisterRepository.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VoteRepository.java
  backend/src/main/java/shook/shook/voting_song/exception/RegisterException.java
  backend/src/main/java/shook/shook/voting_song/exception/VoteException.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/part/application/PartCommentServiceTest.java
  backend/src/test/java/shook/shook/part/application/PartServiceTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentContentTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentTest.java
  backend/src/test/java/shook/shook/part/domain/PartCommentsTest.java
  backend/src/test/java/shook/shook/part/domain/PartTest.java
  backend/src/test/java/shook/shook/part/domain/repository/PartCommentRepositoryTest.java
  backend/src/test/java/shook/shook/part/domain/repository/PartRepositoryTest.java
  backend/src/test/java/shook/shook/part/ui/PartCommentControllerTest.java
  backend/src/test/java/shook/shook/part/ui/PartControllerTest.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/PartsTest.java
  backend/src/test/java/shook/shook/song/domain/SongTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/HighVotedSongControllerTest.java
  backend/src/test/java/shook/shook/song/ui/SongControllerTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongPartServiceTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartTest.java
  backend/src/test/resources/test.sql
Labels: [ 🌙 BE ], 🔨 Refactor

#246 Refactor/#236 VoteInterfaceContext의 partStartTime을 seconds로 관리한다
  frontend/src/features/songs/components/IntervalInput.tsx
  frontend/src/features/songs/components/KillingPartInfo.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/songs/components/VoteInterfaceProvider.tsx
  frontend/src/features/youtube/components/VideoSlider.tsx
  frontend/src/shared/utils/convertTime.test.ts
  frontend/src/shared/utils/convertTime.ts
  frontend/src/shared/utils/validateTime.test.ts
  frontend/src/shared/utils/validateTime.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#253 Feat/#250 styled component에 stylelint를 적용한다
  frontend/.stylelintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/comments/components/Comment.tsx
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/features/songs/components/IntervalInput.tsx
  frontend/src/features/songs/components/KillingPartInfo.tsx
  frontend/src/features/songs/components/KillingPartToggleGroup.tsx
  frontend/src/features/songs/components/PopularSongItem.tsx
  frontend/src/features/songs/components/Thumbnail.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/youtube/components/VideoSlider.tsx
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/components/Layout/Layout.tsx
  frontend/src/shared/components/Modal/Modal.tsx
  frontend/src/shared/components/SRAlert.tsx
  frontend/src/shared/components/SRHeading.tsx
  frontend/src/shared/components/Toast/Toast.tsx
  frontend/src/shared/components/ToggleGroup/ToggleGroup.tsx
  frontend/src/shared/components/ToggleSwitch/ToggleSwitch.tsx
  frontend/src/shared/styles/GlobalStyles.ts
Labels: [ 🌞 FE ], ✨ Feat

#259 Feat/#229 파트 수집 중인 노래 전체 조회, Swipe 용 API 추가
  backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongResponse.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongSwipeResponse.java
  backend/src/main/java/shook/shook/voting_song/domain/repository/VotingSongRepository.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongController.java
  backend/src/test/java/shook/shook/support/AcceptanceTest.java
  backend/src/test/java/shook/shook/support/DataCleaner.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongServiceTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/ui/VotingSongControllerTest.java
Labels: [ 🌙 BE ], ✨ Feat

#271 Fix: cd yml 경로 수정
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
Labels: 🦋 Bug, [ 🌙 BE ], 🤖 InfrA

#272 Hotfix: frontend build ubuntu 유저로 진행
  .github/workflows/frontend-dev-cd.yml
  .github/workflows/frontend-prod-cd.yml
Labels: [ 🌙 BE ], 🔨 Refactor, 🤖 InfrA

#248 Feat/#235 킬링파트 수집 케러셀 컴포넌트 구현
  frontend/src/features/songs/components/CollectionCarousel.stories.tsx
  frontend/src/features/songs/components/CollectionCarousel.tsx
  frontend/src/pages/MainPage.tsx
Labels: [ 🌞 FE ], ✨ Feat

#256 Feat/#249 bottomsheet 모달 적용하여 댓글리스트를 보여준다.
  frontend/src/assets/icon/cancel.svg
  frontend/src/features/comments/components/Comment.tsx
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/shared/components/BottomSheet/BottomSheet.stories.tsx
  frontend/src/shared/components/BottomSheet/BottomSheet.tsx
Labels: [ 🌞 FE ], ✨ Feat

#284 REFACTOR/#283 토큰을 생성하는 방식 수정
  backend/src/main/java/shook/shook/auth/application/AuthService.java
  backend/src/main/java/shook/shook/auth/application/TokenProvider.java
  backend/src/main/java/shook/shook/auth/ui/interceptor/TokenInterceptor.java
  backend/src/main/java/shook/shook/member/application/MemberService.java
  backend/src/main/java/shook/shook/member/domain/repository/MemberRepository.java
  backend/src/test/java/shook/shook/auth/application/AuthServiceTest.java
  backend/src/test/java/shook/shook/auth/application/TokenProviderTest.java
  backend/src/test/java/shook/shook/auth/ui/TokenControllerTest.java
  backend/src/test/java/shook/shook/member/application/MemberServiceTest.java
  backend/src/test/java/shook/shook/song/ui/KillingPartLikeControllerTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#278 Feat/#269 노래 정보 조회 API 구현 (스와이프용)
  backend/src/main/java/shook/shook/member/domain/Member.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
  backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
  backend/src/main/java/shook/shook/song/ui/SongController.java
  backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongSwipeResponse.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/application/killingpart/KillingPartCommentServiceTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/HighLikedSongControllerTest.java
  backend/src/test/java/shook/shook/song/ui/SongControllerTest.java
  backend/src/test/resources/killingpart/initialize_killing_part_song.sql
Labels: [ 🌙 BE ], ✨ Feat

#288 Refactor/#231 MILLIS -> MICROS (소수점 아래 6자리) 수정
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartComment.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
  backend/src/main/java/shook/shook/voting_song/domain/Vote.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSong.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartCommentRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#290 Feat/#287 release drafter를 적용한다.
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: ⚙️ Settin🐁, 🐈‍⬛ Github

#295 Hotfix/#293 이전 노래 조회 쿼리 수정
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
  backend/src/main/java/shook/shook/song/domain/repository/SongRepository.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/SongControllerTest.java
Labels: 🦋 Bug, [ 🌙 BE ]

#294 Refactor/#264: videoUrl -> videoId 변경
  backend/src/main/java/shook/shook/globalexception/ErrorCode.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongWithKillingPartsRegisterRequest.java
  backend/src/main/java/shook/shook/song/domain/Song.java
  backend/src/main/java/shook/shook/song/domain/SongVideoId.java
  backend/src/main/java/shook/shook/song/exception/SongException.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongRegisterRequest.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongResponse.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSong.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/dev/data.sql
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/SongTest.java
  backend/src/test/java/shook/shook/song/domain/SongVideoIdTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartRepositoryTest.java
  backend/src/test/java/shook/shook/song/domain/repository/SongRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/AdminSongControllerTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongPartServiceTest.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongServiceTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongPartsTest.java
  backend/src/test/java/shook/shook/voting_song/domain/VotingSongTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongPartRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/domain/repository/VotingSongRepositoryTest.java
  backend/src/test/java/shook/shook/voting_song/ui/VotingSongControllerTest.java
  backend/src/test/resources/killingpart/initialize_killing_part_song.sql
  backend/src/test/resources/schema-test.sql
  backend/src/test/resources/test.sql
Labels: [ 🌙 BE ], 🔨 Refactor, 💿 Databas🦷

#301 Hotfix/#299 VotingSongSwipeResponse 필드 이름을 수정한다
  backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongSwipeResponse.java
  backend/src/test/java/shook/shook/voting_song/application/VotingSongServiceTest.java
  backend/src/test/java/shook/shook/voting_song/ui/VotingSongControllerTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#307 REFACTOR/#305 쿠키 path 설정 수정
  backend/src/main/java/shook/shook/auth/ui/CookieProvider.java
  backend/src/test/java/shook/shook/auth/ui/AuthControllerTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#303 Feat/#302 모바일에서 인풋 포커스시 확대되지 않도록 수정
  frontend/public/index.html
Labels: [ 🌞 FE ], ✨ Feat

#315 Feat/#279 로그인 구현 및 메인 페이지와 수집 페이지에 적용
  frontend/src/assets/icon/avatar-default.svg
  frontend/src/features/auth/components/AuthProvider.tsx
  frontend/src/features/auth/components/LoginModal.tsx
  frontend/src/features/auth/constants/googleAuthUrl.ts
  frontend/src/features/auth/utils/parseJWT.ts
  frontend/src/features/comments/components/Comment.tsx
  frontend/src/features/comments/components/CommentForm.tsx
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/features/songs/components/CarouselItem.tsx
  frontend/src/features/songs/components/CollectionCarousel.tsx
  frontend/src/features/songs/components/IntervalInput.stories.tsx
  frontend/src/features/songs/components/KillingPartInfo.tsx
  frontend/src/features/songs/components/KillingPartToggleGroup.stories.tsx
  frontend/src/features/songs/components/KillingPartTrack.stories.tsx
  frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
  frontend/src/features/songs/components/PopularSongItem.stories.tsx
  frontend/src/features/songs/components/PopularSongItem.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/songs/components/VoteInterfaceProvider.tsx
  frontend/src/features/songs/remotes/killingPart.ts
  frontend/src/features/songs/remotes/usePostKillingPart.ts
  frontend/src/features/songs/types/Song.type.ts
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/popularSongs.json
  frontend/src/mocks/fixtures/songs.json
  frontend/src/mocks/fixtures/votingSongs.json
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/AuthPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/PartCollectingPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Avatar.tsx
  frontend/src/shared/components/Layout/AuthLayout.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/remotes/index.ts
  frontend/src/shared/types/killingPart.ts
  frontend/src/shared/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#316 Data/#311 QA를 위한 필요한 노래 데이터 추가
  backend/src/main/resources/dev/data.sql
Labels: [ 🌙 BE ], 💿 Databas🦷

#317 Feat/#309 마이페이지를 구현한다
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/pages/MyPage.tsx
  frontend/src/router.tsx
Labels: [ 🌞 FE ], ✨ Feat

#261 Refactor/#244 기존 SongDetailPage 컴포넌트에 새로운 플로우와 시안을 적용한다.
  frontend/package.json
  frontend/src/assets/icon/pause.svg
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/KillingPartTrackList.tsx
  frontend/src/features/songs/components/Thumbnail.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/songs/components/VoteInterfaceProvider.tsx
  frontend/src/features/youtube/components/VideoPlayerProvider.tsx
  frontend/src/features/youtube/components/VideoSlider.tsx
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/shared/components/Timer/TimerProvider.tsx
  frontend/src/shared/components/Timer/hooks/useTimerContext.ts
Labels: [ 🌞 FE ], 🔨 Refactor

#270 Feat/#262 좋아요 기능 구현
  frontend/src/assets/icon/fill-heart.svg
  frontend/src/features/comments/components/CommentForm.tsx
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/songs/components/KillingPartTrack.stories.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/KillingPartTrackList.stories.tsx
  frontend/src/features/songs/components/KillingPartTrackList.tsx
  frontend/src/features/songs/hooks/useKillingPartLikes.ts
  frontend/src/features/songs/remotes/likes.ts
  frontend/src/features/songs/remotes/song.ts
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/shared/hooks/useDebounceEffect.ts
  frontend/src/shared/hooks/useMutation.ts
  frontend/src/shared/remotes/index.ts
  frontend/src/shared/types/song.ts
Labels: [ 🌞 FE ], ✨ Feat

#318 Refactor/#297 예외 발생 시 자세한 에러 로그 생성
  backend/src/main/java/shook/shook/auth/application/TokenProvider.java
  backend/src/main/java/shook/shook/auth/exception/AuthorizationException.java
  backend/src/main/java/shook/shook/auth/exception/OAuthException.java
  backend/src/main/java/shook/shook/auth/exception/TokenException.java
  backend/src/main/java/shook/shook/auth/ui/interceptor/TokenInterceptor.java
  backend/src/main/java/shook/shook/globalexception/CustomException.java
  backend/src/main/java/shook/shook/globalexception/ErrorCode.java
  backend/src/main/java/shook/shook/globalexception/ErrorResponse.java
  backend/src/main/java/shook/shook/globalexception/GlobalExceptionHandler.java
  backend/src/main/java/shook/shook/member/application/MemberService.java
  backend/src/main/java/shook/shook/member/domain/Email.java
  backend/src/main/java/shook/shook/member/domain/Nickname.java
  backend/src/main/java/shook/shook/member/exception/MemberException.java
  backend/src/main/java/shook/shook/member/ui/MemberExceptionHandler.java
  backend/src/main/java/shook/shook/part/domain/PartLength.java
  backend/src/main/java/shook/shook/part/exception/PartException.java
  backend/src/main/java/shook/shook/song/application/SongService.java
  backend/src/main/java/shook/shook/song/application/killingpart/KillingPartCommentService.java
  backend/src/main/java/shook/shook/song/application/killingpart/KillingPartLikeService.java
  backend/src/main/java/shook/shook/song/domain/AlbumCoverUrl.java
  backend/src/main/java/shook/shook/song/domain/KillingParts.java
  backend/src/main/java/shook/shook/song/domain/Singer.java
  backend/src/main/java/shook/shook/song/domain/SongLength.java
  backend/src/main/java/shook/shook/song/domain/SongTitle.java
  backend/src/main/java/shook/shook/song/domain/SongVideoId.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartCommentContent.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartComments.java
  backend/src/main/java/shook/shook/song/exception/SongException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartCommentException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartLikeException.java
  backend/src/main/java/shook/shook/song/exception/killingpart/KillingPartsException.java
  backend/src/main/java/shook/shook/song/ui/SongExceptionHandler.java
  backend/src/main/java/shook/shook/voting_song/application/VotingSongPartService.java
  backend/src/main/java/shook/shook/voting_song/application/VotingSongService.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSong.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongPart.java
  backend/src/main/java/shook/shook/voting_song/domain/VotingSongParts.java
  backend/src/main/java/shook/shook/voting_song/exception/VoteException.java
  backend/src/main/java/shook/shook/voting_song/exception/VotingSongException.java
  backend/src/main/java/shook/shook/voting_song/exception/VotingSongPartException.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongExceptionHandler.java
  backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
  backend/src/test/java/shook/shook/exceptionhandler/ControllerAdviceTest.java
  backend/src/test/java/shook/shook/song/domain/SongVideoIdTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#320 feat: 마이페이지를 위한 멤버의 좋아요한 킬링파트 조회 기능 완성
  backend/src/main/java/shook/shook/auth/config/AuthConfig.java
  backend/src/main/java/shook/shook/song/application/KillingPartService.java
  backend/src/main/java/shook/shook/song/application/dto/LikedKillingPartResponse.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPart.java
  backend/src/main/java/shook/shook/song/domain/killingpart/KillingPartLike.java
  backend/src/main/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepository.java
  backend/src/main/java/shook/shook/song/ui/MyPageController.java
  backend/src/test/java/shook/shook/song/domain/killingpart/repository/KillingPartLikeRepositoryTest.java
  backend/src/test/java/shook/shook/song/ui/MyPageControllerTest.java
Labels: [ 🌙 BE ], ✨ Feat

#319 Feat/#247 스와이프 기능 구현
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/PopularSongItem.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
  frontend/src/features/songs/remotes/songs.ts
  frontend/src/features/youtube/components/VideoPlayerProvider.tsx
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/comments.json
  frontend/src/mocks/fixtures/extraNextSongDetails.json
  frontend/src/mocks/fixtures/extraPrevSongDetails.json
  frontend/src/mocks/fixtures/songEntries.json
  frontend/src/mocks/handlers/songsHandlers.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/pages/SongDetailPage.tsx
  frontend/src/router.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/components/Layout/Layout.tsx
  frontend/src/shared/constants/path.ts
  frontend/src/shared/hooks/useExtraFetch.ts
  frontend/src/shared/hooks/useFetch.ts
  frontend/src/shared/remotes/index.ts
  frontend/src/shared/styles/theme.ts
  frontend/src/shared/types/song.ts
  frontend/webpack.dev.js
Labels: [ 🌞 FE ], ✨ Feat

#327 Feat/#309 마이페이지에서 유저 닉네임 표시와 로그아웃 가능
  frontend/src/pages/MyPage.tsx
  frontend/src/router.tsx
Labels: [ 🌞 FE ], ✨ Feat

#334 Fix/#329 모달로 인해 불필요한 div 가 dom에 추가되는 현상 수정
  frontend/src/shared/components/BottomSheet/BottomSheet.tsx
  frontend/src/shared/components/Modal/Modal.tsx
Labels: [ 🌞 FE ], ✨ Feat

#338 refactor: votingSongs 곡이 없을경우 안내메세지
  frontend/src/pages/MainPage.tsx
Labels: [ 🌞 FE ], ✨ Feat

#341 Refactor/#340: 노래 안의 킬링파트 조회 시, 좋아요 순 - 시작 시간 순으로 조회
  backend/src/main/java/shook/shook/song/domain/KillingParts.java
  backend/src/test/java/shook/shook/song/application/SongServiceTest.java
  backend/src/test/java/shook/shook/song/domain/killingpart/KillingPartsTest.java
Labels: [ 🌙 BE ], 🔨 Refactor

#339 Hotfix: killing_part like_count 디폴트값 추가
  backend/src/main/resources/dev/schema.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/shook/shook/auth/ui/AccessTokenReissueControllerTest.java
  backend/src/test/resources/killingpart/initialize_killing_part_song.sql
  backend/src/test/resources/schema-test.sql
Labels: [ 🌙 BE ], 💿 Databas🦷

#332 Refactor/#331 오류 로깅 시 메세지와 에러 코드 포함
  backend/src/main/java/shook/shook/globalexception/CustomException.java
  backend/src/main/java/shook/shook/globalexception/GlobalExceptionHandler.java
Labels: [ 🌙 BE ], 🔨 Refactor

#343 Feat/#337 스와이프 페이지 이동 시 기존 재생 노래 멈춤 기능을 구현한다.
  frontend/src/features/songs/components/KillingPartInterface.tsx
  frontend/src/features/youtube/components/Youtube.tsx
Labels: [ 🌞 FE ], ✨ Feat

#345 fix: like 개수 상태를 두어 새로고침 뒤에 정합성 유지
  frontend/src/features/songs/hooks/useKillingPartLikes.ts
Labels: [ 🌞 FE ], ✨ Feat

#344 Feat/#263 swagger 명세서를 작성한다.
  backend/src/main/java/shook/shook/auth/application/dto/ReissueAccessTokenResponse.java
  backend/src/main/java/shook/shook/auth/ui/AccessTokenReissueController.java
  backend/src/main/java/shook/shook/auth/ui/AuthController.java
  backend/src/main/java/shook/shook/auth/ui/dto/LoginResponse.java
  backend/src/main/java/shook/shook/auth/ui/openapi/AccessTokenReissueApi.java
  backend/src/main/java/shook/shook/auth/ui/openapi/AuthApi.java
  backend/src/main/java/shook/shook/config/OpenApiConfig.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/dto/KillingPartResponse.java
  backend/src/main/java/shook/shook/song/application/dto/LikedKillingPartResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongSwipeResponse.java
  backend/src/main/java/shook/shook/song/application/dto/SongWithKillingPartsRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/HighLikedSongResponse.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/KillingPartCommentRegisterRequest.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/KillingPartCommentResponse.java
  backend/src/main/java/shook/shook/song/application/killingpart/dto/KillingPartLikeRequest.java
  backend/src/main/java/shook/shook/song/ui/AdminSongController.java
  backend/src/main/java/shook/shook/song/ui/HighLikedSongController.java
  backend/src/main/java/shook/shook/song/ui/KillingPartCommentController.java
  backend/src/main/java/shook/shook/song/ui/KillingPartLikeController.java
  backend/src/main/java/shook/shook/song/ui/MyPageController.java
  backend/src/main/java/shook/shook/song/ui/SongController.java
  backend/src/main/java/shook/shook/song/ui/openapi/AdminSongApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/HighLikedSongApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/KillingPartCommentApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/KillingPartLikeApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/MyPageApi.java
  backend/src/main/java/shook/shook/song/ui/openapi/SongApi.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongPartRegisterRequest.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongRegisterRequest.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongResponse.java
  backend/src/main/java/shook/shook/voting_song/application/dto/VotingSongSwipeResponse.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongController.java
  backend/src/main/java/shook/shook/voting_song/ui/VotingSongPartController.java
  backend/src/main/java/shook/shook/voting_song/ui/openapi/VotingSongApi.java
  backend/src/main/java/shook/shook/voting_song/ui/openapi/VotingSongPartApi.java
Labels: [ 🌙 BE ], ✍️ Docs

#347 design: 수집페이지에서 텍스트가 긴 경우 ellipsis 적용
  frontend/src/pages/PartCollectingPage.tsx
Labels: 🦋 Bug, [ 🌞 FE ]

#348 fix: safari에서 폰트가 적용되지 않던 버그 수정
  frontend/src/shared/styles/GlobalStyles.ts
Labels: 🦋 Bug, [ 🌞 FE ]

#349 Fix/#342 420px(모바일 break point) 외의 사이즈에서 스와이프가 작동하지 않는 오류
  frontend/src/features/comments/components/CommentList.tsx
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/SongDetailItem.tsx
  frontend/src/features/songs/components/VoteInterface.tsx
  frontend/src/features/youtube/components/Youtube.tsx
  frontend/src/pages/SongDetailListPage.tsx
  frontend/src/shared/components/Avatar.tsx
  frontend/src/shared/components/Layout/Header.tsx
  frontend/src/shared/components/Layout/Layout.tsx
  frontend/src/shared/styles/GlobalStyles.ts
  frontend/src/shared/styles/theme.ts
Labels: 🦋 Bug, ✨ Feat

#350 fix: 디자인 핫픽스
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/PartCollectingPage.tsx
Labels: 🦋 Bug, [ 🌞 FE ]
