Repository woowacourse-teams/2023-shook, pull requests merged in 2024-04, with the labels that each got.

#556 Refactor/#555 프로젝트 동의를 구하는 모달을 confirmModal로 리팩터링
  frontend/src/features/killingParts/components/RegisterPart.tsx
  frontend/src/features/member/components/WithdrawalModal.tsx
  frontend/src/features/member/constants/withdrawalMessage.ts
  frontend/src/features/songs/components/KillingPartTrack.tsx
  frontend/src/features/songs/components/MyPartModal.tsx
  frontend/src/index.tsx
  frontend/src/pages/EditProfilePage.tsx
  frontend/src/shared/components/ConfirmModal/ConfirmModal.tsx
Labels: [ 🌞 FE ], 🔨 Refactor

#564 Fix/#563 머지 컨플릭트 해결
  frontend/src/features/killingParts/components/RegisterPart.tsx
  frontend/src/pages/EditProfilePage.tsx
Labels: 🦋 Bug, [ 🌞 FE ]

#567 Feat/#566 overlay를 다룰 useOverlay 훅 구현
  frontend/src/router.tsx
  frontend/src/shared/hooks/useOverlay/OverlayController.tsx
  frontend/src/shared/hooks/useOverlay/OverlayProvider.tsx
  frontend/src/shared/hooks/useOverlay/index.ts
  frontend/src/shared/hooks/useOverlay/types.ts
  frontend/src/shared/hooks/useOverlay/useOverlay.tsx
Labels: [ 🌞 FE ], ✨ Feat
